Discovering IEntityMap<> implementations dynamically
henkmollema/Dapper-FluentMap pull request #128
Opened 2020-11-26 12:07 UTC by vecilije

@henkmollema I came with this solution when I was using your library while working with Dapper, and wanted to suggest it to you if that might be interesting. The implementation itself is a **FluentMapConfiguration** extension method which gives possibility to automatically discover types implementing **IEntityMap<>** for specific assemblies, so there is no need to add them manually (usually everyone will be inheriting from EntityMap<>, but it is implementing IEntityMap) . Usage:
```c#
FluentMapper.Configure(c => 
{
  c.ApplyMapsFromAssemblies(assemblies); // 
});
```

2021-06-02 12:15 UTC, henkmollema commented on src/Dapper.FluentMap/Utils/FluentMapConfigurationExtensions.cs
> +            params Assembly[] assemblies)
Can you put these parameters on a single line?

2021-06-02 12:18 UTC, henkmollema requested changes
Nice work! Could you take a look at a few nits about code style?

2021-06-02 12:18 UTC, henkmollema commented on src/Dapper.FluentMap/Utils/FluentMapConfigurationExtensions.cs
> +            params Assembly[] assemblies)
```suggestion
        public static void ApplyMapsFromAssemblies(this FluentMapConfiguration configuration,  params Assembly[] assemblies)
```

Can you put the parameters on a single line?

2021-06-02 12:18 UTC, henkmollema commented on src/Dapper.FluentMap/Utils/FluentMapConfigurationExtensions.cs
> +            if (assemblies == null)
Can you add parentheses around single line `if`/`foreach` blocks?

2021-06-02 12:18 UTC, henkmollema commented on src/Dapper.FluentMap/Utils/FluentMapConfigurationExtensions.cs
> +        /// <param name="configuration">The <see cref="FluentMapConfiguration"/> instance</param>
```suggestion
        /// <param name="configuration">The <see cref="FluentMapConfiguration"/> instance.</param>
```

2021-06-02 12:18 UTC, henkmollema commented on src/Dapper.FluentMap/Utils/FluentMapConfigurationExtensions.cs
> +        /// <param name="assemblies">Assemblies</param>
```suggestion
        /// <param name="assemblies">The assemblies to scan for entity maps.</param>
```

2021-06-02 12:18 UTC, henkmollema commented on src/Dapper.FluentMap/Utils/FluentMapConfigurationExtensions.cs
> +        /// <exception cref="ArgumentNullException"></exception>
Can you either clarify the exception or remove the XML doc node?

2021-06-02 12:18 UTC, henkmollema commented on src/Dapper.FluentMap/Utils/FluentMapConfigurationExtensions.cs
> +    /// Extension methods for <see cref="FluentMapConfiguration"/>
```suggestion
    /// Extension methods for <see cref="FluentMapConfiguration"/>.
```

2021-06-08 14:34 UTC, vecilije commented
Hi @henkmollema , thank you very much for considering this change. I based on your recommendations. Hope everything is fine now.

2021-09-17 22:42 UTC, xthrush commented
I would like to support this change. in a finished form.

2021-11-04 08:57 UTC, henkmollema approved these changes
Thanks!

2021-11-04 08:57 UTC, merged